# Generated by Django 3.2.20 on 2023-08-05 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('noise', models.IntegerField(blank=True, default=0)),
                ('cleanness', models.IntegerField(blank=True, default=0)),
                ('accessibility', models.IntegerField(blank=True, default=0)),
                ('facility', models.IntegerField(blank=True, default=0)),
                ('average', models.FloatField(blank=True, default=0.0)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
