# Generated by Django 3.2.20 on 2023-08-05 12:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='post',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='accessibility',
            field=models.IntegerField(blank=True, default=0, verbose_name='접근성'),
        ),
        migrations.AlterField(
            model_name='post',
            name='average',
            field=models.FloatField(blank=True, default=0.0, verbose_name='평균'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cleanness',
            field=models.IntegerField(blank=True, default=0, verbose_name='청결도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility',
            field=models.IntegerField(blank=True, default=0, verbose_name='시설 및 장비'),
        ),
        migrations.AlterField(
            model_name='post',
            name='noise',
            field=models.IntegerField(blank=True, default=0, verbose_name='소음'),
        ),
    ]
