# Generated by Django 3.2.20 on 2023-08-08 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_auto_20230806_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationComment',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('noise', models.IntegerField(blank=True, default=0, verbose_name='소음')),
                ('cleanness', models.IntegerField(blank=True, default=0, verbose_name='청결도')),
                ('accessibility', models.IntegerField(blank=True, default=0, verbose_name='접근성')),
                ('facility', models.IntegerField(blank=True, default=0, verbose_name='시설 및 장비')),
                ('average', models.FloatField(blank=True, default=0.0, verbose_name='평균')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('brchCd', models.IntegerField()),
                ('brchNm', models.CharField(max_length=100)),
                ('examAreaGbNm', models.CharField(max_length=100)),
                ('examAreaNm', models.CharField(max_length=100)),
                ('plceLoctGid', models.CharField(max_length=500)),
                ('telNo', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
