# Generated by Django 3.2.20 on 2023-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20230808_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationinfo',
            name='brchCd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='longtitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='plceLoctGid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='telNo',
            field=models.CharField(max_length=100),
        ),
    ]
