# Generated by Django 3.2.20 on 2023-08-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20230809_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcomment',
            old_name='pid',
            new_name='location_comment_id',
        ),
        migrations.RenameField(
            model_name='locationcomment',
            old_name='reviewer',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='locationcomment',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.locationinfo'),
        ),
    ]
