# Generated by Django 3.2.20 on 2023-08-11 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecent',
            fields=[
                ('recent_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamFavorite',
            fields=[
                ('favorite_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
