# Generated by Django 3.2.20 on 2023-08-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examfavorite_examrecent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='exam',
            name='mdobligfldcd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mdobligfldnm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='obligfldcd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='obligfldnm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='docExamEndDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='docExamStartDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='docPassDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='docRegEndDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='docRegStartDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='pracExamEndDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='pracExamStartDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='pracPassDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='pracRegEndDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplan',
            name='pracRegStartDt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examrecent',
            name='recent_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
